# Generated by Django 3.2.5 on 2021-09-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='address',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='name',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='phone',
        ),
    ]
