# Generated by Django 3.2.5 on 2021-09-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crud_operations', '0002_auto_20210907_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='Address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='crud',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crud',
            name='Alternate_Email_Id',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Alternate_Mobile_Number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Branch_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Emai_Id',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Father_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='First_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Institute_Name',
            field=models.CharField(choices=[('itnu', 'ITNU'), ('imnu', 'IMNU')], default='imnu', max_length=10),
        ),
        migrations.AddField(
            model_name='crud',
            name='Last_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Middle_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Mobile_Number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crud',
            name='Mother_Name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
