# Generated by Django 4.1 on 2022-11-01 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'StateLists'},
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updatedon'),
        ),
        migrations.AlterModelTable(
            name='state',
            table='stae',
        ),
    ]
