# Generated by Django 4.1 on 2022-11-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_alter_state_options_alter_state_updated_on_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='state',
        ),
    ]
