# Generated by Django 4.1 on 2022-11-01 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_user_password_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(2022, 11, 1), verbose_name='Date'),
        ),
    ]
