# Generated by Django 4.1 on 2022-11-16 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'active'), (0, 'inactive')], default=1, help_text='1->active, 0->inactive', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(2022, 11, 16), verbose_name='Date'),
        ),
    ]
