# Generated by Django 4.1 on 2022-11-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislike',
            field=models.IntegerField(default=0, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0, editable=False, max_length=10),
        ),
    ]
