# Generated by Django 3.2.5 on 2022-10-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20221031_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State List'},
        ),
    ]
