# Generated by Django 4.1 on 2022-10-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
