# Generated by Django 4.1 on 2022-10-31 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_alter_state_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'StateList'},
        ),
        migrations.AlterField(
            model_name='state',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updatedon'),
        ),
    ]
